config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  root to: "projects#index"
  resources :tasks
  resources :projects
  resources :project_phases
  get 'project_phases/create'

  get 'projects/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
	extend FriendlyId
  friendly_id :name, use: :slugged
	validates_presence_of :name,
												:context_id,
												:priority_id,
												:project_phase_id,
												:review_period_id,
												:status_id

	belongs_to :project_phase
	belongs_to :context
	belongs_to :priority
	belongs_to :review_period
	belongs_to :status
	belongs_to :user
	has_one :project, through: :project_phase
	has_and_belongs_to_many :tags

	accepts_nested_attributes_for :project_phase,
																reject_if: lambda { |attrs| attrs["name"].blank? }
	accepts_nested_attributes_for :context,
																reject_if: lambda { |attrs| attrs["context"].blank? }
	accepts_nested_attributes_for :priority,
																reject_if: lambda { |attrs| attrs["priority_id"].blank? }
	accepts_nested_attributes_for :review_period,
																reject_if: lambda { |attrs| attrs["review_period_id"].blank? }
	accepts_nested_attributes_for :status,
																reject_if: lambda { |attrs| attrs["status_id"].blank? }

	scope :by_project_phase_id_range, ->(min, max) { where(project_phase_id: min..max)}

=begin
	enum context_id: { meeting: 1, communication: 2, information_work: 3, knowledge_work: 4, learning: 5, errand: 6, chore:7}
	enum priority_id: { top: 1, high: 2, normal: 3, low: 4}
	enum review_period_id: { weekly: 3, monthly: 4, quarterly: 5, yearly: 6}
	enum status_id: { active: 1, completed: 2, abandoned: 3, next_project: 4}
=end

	after_initialize :set_defaults

	def set_defaults
		self.name ||= "New Task"
		self.due_date ||= Time.now.strftime('%Y-%m-%d %H:%M:%S')
	end

	def self.sorted(direction:)
		Task.order("name " + direction)
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout "application"
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    if @task.save!
      flash.now[:notice] = 'Task was successfully created.'
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        flash.now[:notice] = 'Task was successfully updated.'
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to action: "index", notice: 'Task was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name,
                                  :description,
                                  :due_date,
                                  :link,
                                  :attachment,
                                  :context_id,
                                  :review_period_id,
                                  :priority_id,
                                  :project_phase_id,
                                  :status_id,
                                  :user_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
.form-group#form-text-color
  = bootstrap_form_for @task, remote: true, class: "row", url: { :controller => "tasks", :action => "create"  } do |f|
    %h3 New Task
    .row
      .col-md-8
        %p
        = f.hidden_field :user_id, value: current_user.id
        = f.text_field :name
        = f.text_area :description, size: "10x5"
      .col-md-4
        = collection_select( :task, :status_id, ::Status.all, :id, :status_id, {}, { :multiple => false } )
        %br/
        = collection_select( :task, :context_id, ::Context.all, :id, :context_id, {}, { :multiple => false } )
        %br/
        = collection_select( :task, :project_phase_id, ::ProjectPhase.all, :id, :name, {}, { :multiple => false } )
        %br/
        = collection_select( :task, :review_period_id, ::ReviewPeriod.all, :id, :review_period_id, {}, { :multiple => false } )
        %br/
        = collection_select( :task, :priority_id, ::Priority.all, :id, :priority_id, {}, { :multiple => false } )
        %br/
        = f.datetime_field :due_date
        = f.text_field :link
      .col-12
        .float-center
          = f.submit "Create", class: "create_task_btn btn btn-primary"
          %button.close-form-btn.btn.btn-primary Back

app/views/tasks/create.js.haml
$('#task-form').slideUp(250);
$("#form-title").delay(250).slideUp(50);
$(".nav-list").delay(300).slideDown(100);
$("#new_link").delay(400).slideDown(50);

app/views/tasks/edit.html.haml
= render 'form'

= link_to 'Show', @task

= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Coming Soon!

app/views/tasks/new.html.haml
%h3 New Task

= render 'form', task: @task

= link_to 'Back', tasks_path

app/views/tasks/new.js.haml
$("#new_link").hide();
$('#task-form').html("#{j (render 'form')}");
$(".nav-list").slideUp(100);
$("#form-title").delay(100).slideDown(50);
$('#task-form').delay(150).slideDown(250);

app/views/tasks/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @task.name
%p
  %strong Description:
  = @task.description
%p
  %strong Due date:
  = @task.due_date
%p
  %strong Link:
  = @task.link
%p
  %strong Attachment:
  = @task.attachment
= link_to 'Edit', edit_task_path(@task)
= link_to 'Back', tasks_path