config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  root to: "projects#index"
  resources :tasks
  resources :projects
  resources :project_phases
  get 'project_phases/create'

  get 'projects/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_login-notice.html.haml
.row
  .col
    %p.notice.alert
      = notice
      = alert
  .col
    - if current_user
      .btn.btn-default.float-right= link_to "Log Out", destroy_user_session_path, method: :delete
    - else
      .btn.btn-default.float-right= link_to "Register", new_user_registration_path
      .btn.btn-default.float-right= link_to "Log In", new_user_session_path

app/views/shared/_navbar.html.haml
.col-md-3.navigation-bar.text-center.overflow-scroll
  .container.nav-container
    %ul.nav-list.float-center
      %li.nav-item
        %a{:href => "/tasks"} Tasks
      %li.nav-item
        %a{:href => "/projects"} Projects
      %li.nav-item
        %a{:href => "/project_phases"} Project Phases
      %li.nav-item
        %a{:href => "#"} Lorem
      %li.nav-item
        %a{:href => "#"} Ipsum
      %li.nav-item
        %a{:href => "#"} Dolor
  - if controller.controller_name == "tasks"
    %h3#form-title.nav-text-color{:style => "display: none"} New Task
  - elsif controller.controller_name == "projects"
    %h3#form-title.nav-text-color{:style => "display: none"} New Project
  - elsif controller.controller_name == "project_phases"
    %h3#form-title.nav-text-color{:style => "display: none"} New Project Phase
  #task-form{:style => "display:none;"}
  .nav-item#bottom-of-page.new-task-button
    - if controller.controller_name == "tasks"
      = link_to "New Task", new_task_path, id: "new_link", remote: true
    - elsif controller.controller_name == "projects"
      = link_to "New Project", new_project_path, id: "new_link", remote: true
    - elsif controller.controller_name == "project_phases"
      = link_to "New Project Phase", new_project_phase_path, id: "new_link", remote: true

app/views/shared/_new_task.haml
.task-card.card
  .card-body.task-card-body
    %p= link_to "New Task", new_task_path, class: "new-task-link"

app/views/shared/_task.haml
.task-card.card
  .card-body.task-card-body
    %ul.task-list
      %li.task-list-item
        %strong= task.name
      %li.task-list-item= task.description
      %li.task-list-item
        Due Date:
        = time_ago_in_words(task.due_date)