config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  root to: "projects#index"
  resources :tasks
  resources :projects
  resources :project_phases
  get 'project_phases/create'

  get 'projects/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/project_phases_controller.rb
class ProjectPhasesController < ApplicationController
  before_action :set_project_phase, only: [:show, :edit, :update, :destroy]

  # GET /project_phases
  # GET /project_phases.json
  def index
    @project_phases = ProjectPhase.all
  end

  # GET /project_phases/1
  # GET /project_phases/1.json
  def show
  end

  # GET /project_phases/new
  def new
    @project_phase = ProjectPhase.new
  end

  # GET /project_phases/1/edit
  def edit
  end

  # POST /project_phases
  # POST /project_phases.json
  def create
    @project_phase = ProjectPhase.new(project_phase_params)

    respond_to do |format|
      if @project_phase.save
        format.html { redirect_to action: "index", notice: 'Project phase was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /project_phases/1
  # PATCH/PUT /project_phases/1.json
  def update
    respond_to do |format|
      if @project_phase.update(project_phase_params)
        format.html { redirect_to action: "index", notice: 'Project phase was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /project_phases/1
  # DELETE /project_phases/1.json
  def destroy
    @project_phase.destroy
    respond_to do |format|
      format.html { redirect_to action: "index", notice: 'Project phase was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_phase
      @project_phase = ProjectPhase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_phase_params
      params.require(:project_phase).permit(:name,
                                            :description,
                                            :project_id)
    end
end

app/helpers/project_phases_helper.rb
module ProjectPhasesHelper
end

app/views/project_phases/_form.html.haml
.form-group#form-text-color
  = bootstrap_form_for @project_phase, remote: true, url: { action: "create"} do |f|
    = f.text_field :name
    = f.text_area :description
    = collection_select( :project_phase, :project_id, ::Project.all, :id, :name, {}, { :multiple => false } )
    %br
    = f.submit "Create"
%button.close-form-btn.btn.btn-primary Back

:javascript
  $(document).ready( function() {
    $(".close-form-btn").click( function() {
      $('#task-form').slideUp(250);
      $("#form-title").delay(250).slideUp(50);
      $(".nav-list").delay(300).slideDown(100);
      $("#new_link").delay(400).slideDown(50);
    });
  });

app/views/project_phases/create.html.haml
%h1 ProjectPhases#create
%p Find me in app/views/project_phases/create.html.haml

app/views/project_phases/create.js.erb
$('#task-form').slideUp(250);
$("#form-title").delay(250).slideUp(50);
$(".nav-list").delay(300).slideDown(100);
$("#new_link").delay(400).slideDown(50);

app/views/project_phases/create.js.haml
$('#task-form').slideUp(250);
$("#form-title").delay(250).slideUp(50);
$(".nav-list").delay(300).slideDown(100);
$("#new_link").delay(400).slideDown(50);

app/views/project_phases/edit.html.haml
%h1 Editing project_phase

= render 'form'

= link_to 'Show', @project_phase
\|
= link_to 'Back', project_phases_path

app/views/project_phases/index.html.haml
= render "shared/navbar"
.col-md-9.content-col#full-height
  =render "shared/login-notice"
  %h3 Project Phases

  %table.table{ :align => "right"}
    %thead
      %tr
        %th Name
        %th Description
        %th

    %tbody
      - @project_phases.each do |project_phase|
        %tr
          %td= project_phase.name
          %td= project_phase.description
          %td
            = link_to 'Show', project_phase
            = link_to 'Edit', edit_project_phase_path(project_phase)
            = link_to 'Destroy', project_phase, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/project_phases/new.html.haml
%h1 New project_phase

= render 'form'

= link_to 'Back', project_phases_path

app/views/project_phases/new.js.erb
$("#new_link").hide();
$('#task-form').html("<%= j (render 'form') %>");
$(".nav-list").slideUp(100);
$("#form-title").delay(100).slideDown(50);
$('#task-form').delay(150).slideDown(250);

app/views/project_phases/new.js.haml
$("#new_link").hide();
$('#task-form').html("#{j (render 'form')}");
$(".nav-list").slideUp(100);
$("#form-title").delay(100).slideDown(50);
$('#task-form').delay(150).slideDown(250);

app/views/project_phases/show.html.haml
%p#notice= notice
%h1= @project_phase.name
%p
  %strong Description:
  = @project_phase.description
%h2 Tasks:
%table
  %tr
    %th Due Date
    %th Name
    %th Description
    - ::Task.all.where("project_phase_id = ?", params[:project_phase_id]).order('due_date ASC').each do |task|
      %td= task.due_date
      %td= task.name
      %td= task.description

= link_to 'Edit', edit_project_phase_path(@project_phase)
= link_to 'Back', project_phases_path